name: Build and Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  dist:
    name: "Build distribution release."
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the repository."
        uses: "actions/checkout@v2"

      - name: "Set up Node.js."
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: "Cache NPM dependencies"
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "Check if package-lock.json is in sync"
        run: |
          if [ -f package.json ]; then
            if ! npm install --dry-run; then
              echo "package-lock.json is out of sync with package.json"
              exit 1
            fi
          fi

      - name: "Install NPM dependencies"
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
          else
            echo "No package.json file found, skipping npm install."
          fi

      - name: "Build release: Stable if package.json exists."
        run: |
          if [ -f package.json ]; then
            npm run build
          else
            echo "No package.json file found, skipping npm run build."
          fi

      - name: "Remove files based on .distignore"
        run: |
          if [ -f .distignore ]; then
            cat .distignore | xargs rm -rf
          else
            echo ".distignore file not found."
          fi

      - name: "Create a Release Archive"
        run: |
          zip -r test-selfhost.zip .

      - name: "Create a GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          files: test-selfhost.zip
        env:
          GITHUB_TOKEN: ${{ secrets.SELFHOST_TOKEN }}  # Ensure this token has the right permissions