name: Build and Release

on:
  push:
    tags:
      - '[0-9]+*.[0-9]+*'  # Matches tags with numbers and decimals such as 1, 2, 1.2, 1.1, 2.0, etc.

jobs:
  dist:
    name: "Build distribution release."
    runs-on: ubuntu-latest

    steps:
      - name: "Checks out the repository."
        uses: "actions/checkout@v2"

      - name: "Setup NodeJS."
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use the latest LTS version of Node.js

      - name: "Cache NPM directory"
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-npm-

      - name: "Cache node_modules"
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node-modules-

      - name: "Install NPM dependencies"
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: "Build release: Stable"
        run: npm run build

      - name: "Copy files to distribution directory excluding .distignore entries"
        run: |
          mkdir -p dist
          rsync -a --delete --exclude-from='.distignore' --exclude='dist/' --exclude='node_modules/' ./ dist/

      - name: "Create a Release Archive"
        run: |
          cd dist
          zip -r ../test.zip . -x "node_modules/*"

      - name: "Create a GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          files: test.zip
        env:
          GITHUB_TOKEN: ${{ secrets.SELFHOST_TOKEN }}  # Ensure this token has the right permissions